In [32]:
import networkx as nx
import numpy as np

In [33]:
G = nx.Graph()
V = {'A','B','C','D','E'}
E = [('A','B'),('A','C'),('A','D'),('A','E'),('B','C'),('B','D')]

In [34]:
G.add_nodes_from(V)
G.add_edges_from(E)

In [35]:
print(G.nodes)

['A', 'C', 'E', 'B', 'D']


In [36]:
print(f"Graph Order; {G.number_of_edges()}")
print(f"Graph Size; {G.number_of_nodes()}")

Graph Order; 6
Graph Size; 5


In [37]:
for V in G.nodes:
  print(V, G.degree(V))

A 4
C 2
E 1
B 3
D 2


###Homework

##Ex 1: Directed gragh G = (V,E)
###a) Find adjacency matrix



In [72]:
G = nx.Graph()
V = ['A','B','C','D','E']
E = [('A','B'),('A','C'),('A','D'),('A','E'),('B','C'),('B','E'),('B','D')]

In [73]:
n = len(V)

In [74]:
adj = np.zeros((n,n))
adj

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [75]:
city_index = {V[i]:i for i in range(len(V))}
city_index

{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4}

In [76]:
for i in E:
  x = city_index[i[0]]
  y = city_index[i[1]]
  adj[x][y] = 1

In [77]:
adj

array([[0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

###b) Tính indegree, outdegree mỗi node, lưu thông tin dưới dạng dict

In [78]:
in_ = np.sum(adj, axis = 0)
in_

array([0., 1., 2., 2., 2.])

In [79]:
out_ = np.sum(adj, axis = 1)
out_

array([4., 3., 0., 0., 0.])

In [80]:
indegree = {}
indegree

{}

##Ex 2: Cho weighted graph G=(V,E,w). Implement thuật toán dijsktra bằng python để tìm đường đi ngắn nhất giữa 2 nodes, tự tạo 1 graph, có nhiều path giữa 2 nodes và test thử.